### ISSUE TITLE
Unable to create environment

### ISSUE THREAD

**Issue by hanspaa2017108** [xg-chu/GAGAvatar#12]
![image](https://github.com/user-attachments/assets/0aa2f03d-b7af-45e4-accf-150c2db98952)
![image](https://github.com/user-attachments/assets/373c92ad-62cf-4b71-8c17-9016664ecc3f)

Hi, I'm unable to create environment, this is on my windows local machine. Same errors for EC2 windows and linux instances
Any Troubleshoot?

Thanks

Error-
(base) C:\Users\hansp\files\GAGAvatar>conda env create -f environment.yml
Channels:
 - pytorch3d
 - pytorch
 - nvidia
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.5.5=hc292b87_2
  - zlib==1.2.13=h4ab18f5_6
  - yaml==0.2.5=h7b6447c_0
  - xz==5.4.6=h5eee18b_1
  - wheel==0.44.0=py312h06a4308_0
  - urllib3==2.2.2=py312h06a4308_0
  - typing_extensions==4.11.0=py312h06a4308_0
  - typing-extensions==4.11.0=py312h06a4308_0
  - tqdm==4.66.5=py312he106c6f_0
  - torchtriton==3.0.0=py312
  - tk==8.6.14=h39e8969_0
  - tbb==2021.8.0=hdb19cb5_0
  - sympy==1.13.2=py312h06a4308_0
  - sqlite==3.45.3=h5eee18b_0
  - setuptools==75.1.0=py312h06a4308_0
  - requests==2.32.3=py312h06a4308_0
  - readline==8.2=h5eee18b_0
  - pyyaml==6.0.1=py312h5eee18b_0
  - pytorch3d==0.7.8=py312_cu121_pyt241
  - pytorch-cuda==12.1=ha16c6d3_5
  - pytorch==2.4.1=py3.12_cuda12.1_cudnn9.1.0_0
  - python==3.12.2=hab00c5b_0_cpython
  - pysocks==1.7.1=py312h06a4308_0
  - protobuf==4.25.3=py312h83439f5_1
  - pip==24.2=py312h06a4308_0
  - pillow==10.4.0=py312h5eee18b_0
  - packaging==24.1=py312h06a4308_0
  - openssl==3.3.2=hb9d3cd8_0
  - openjpeg==2.5.2=he7f1fd0_0
  - openh264==2.1.1=h4ff587b_0
  - onnx==1.16.2=py312h8302a36_1
  - numpy-base==1.26.4=py312h0da6c21_0
  - numpy==1.26.4=py312hc5e2394_0
  - networkx==3.2.1=py312h06a4308_0
  - nettle==3.7.3=hbbd107a_1
  - ncurses==6.4=h6a678d5_0
  - mpmath==1.3.0=py312h06a4308_0
  - mkl_random==1.2.7=py312h526ad5a_0
  - mkl_fft==1.3.10=py312h5eee18b_0
  - mkl-service==2.4.0=py312h5eee18b_1
  - mkl==2023.1.0=h213fc3f_46344
  - markupsafe==2.1.3=py312h5eee18b_0
  - lz4-c==1.9.4=h6a678d5_1
  - llvm-openmp==14.0.6=h9e868ea_0
  - libzlib==1.2.13=h4ab18f5_6
  - libxcrypt==4.4.36=hd590300_1
  - libwebp-base==1.3.2=h5eee18b_0
  - libuuid==2.38.1=h0b41bf4_0
  - libunistring==0.9.10=h27cfd23_0
  - libtiff==4.5.1=h6a678d5_0
  - libtasn1==4.19.0=h5eee18b_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - libstdcxx==14.1.0=hc0a3c3a_1
  - libsqlite==3.46.0=hde9e2c9_0
  - libprotobuf==4.25.3=he621ea3_0
  - libpng==1.6.39=h5eee18b_0
  - libnsl==2.0.1=hd590300_0
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - libidn2==2.3.4=h5eee18b_0
  - libiconv==1.16=h5eee18b_3
  - libgomp==14.1.0=h77fa898_1
  - libgcc-ng==14.1.0=h69a702a_1
  - libgcc==14.1.0=h77fa898_1
  - libffi==3.4.4=h6a678d5_1
  - libfaiss==1.8.0=h046e95b_0_cuda12.1.1
  - libexpat==2.6.3=h5888daf_0
  - libdeflate==1.17=h5eee18b_1
  - libcufile==1.11.1.6=0
  - libabseil==20240116.2=cxx17_h6a678d5_0
  - lerc==3.0=h295c915_0
  - ld_impl_linux-64==2.40=h12ee557_0
  - lcms2==2.12=h3be6417_0
  - lame==3.100=h7b6447c_0
  - jpeg==9e=h5eee18b_3
  - jinja2==3.1.4=py312h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - idna==3.7=py312h06a4308_0
  - gnutls==3.6.15=he1e5248_0
  - gmp==6.2.1=h295c915_3
  - freetype==2.12.1=h4a9f257_0
  - filelock==3.13.1=py312h06a4308_0
  - ffmpeg==4.3=hf484d3e_0
  - faiss-gpu==1.8.0=py3.12_h4c7d538_0_cuda12.1.1
  - expat==2.6.3=h6a678d5_0
  - certifi==2024.8.30=py312h06a4308_0
  - ca-certificates==2024.8.30=hbcca054_0
  - bzip2==1.0.8=h5eee18b_6
  - brotli-python==1.0.9=py312h6a678d5_8
  - _libgcc_mutex==0.1=conda_forge

Current channels:

  - https://conda.anaconda.org/pytorch3d/win-64
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/nvidia/win-64
  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by xg-chu** [comment]
I have not tried to build this env on Windows PC, but Linux with CUDA should work.
For Windows env, maybe you can try to build it from scratch.
 - The first key part is installing PyTorch3D: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md.
 - Then compile the 3DGS renderer with CUDA.
 - The rest of the packages are quite easy to install.

**Comment by hanspaa2017108** [comment]
thanks, it worked @xg-chu
