### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xz0305** [xg-chu/GAGAvatar#15]
Hello, after reading your paper, I'm having some difficulty understanding this part: 'the rotation of the head is modeled through changes in camera pose to ensure that the head itself is relatively stationary.' Why is the head movement described using camera pose instead of directly modifying the head's movement? What is the reason for keeping the head stationary?

**Comment by xg-chu** [comment]
In order to keep the head static in the 3D canonical space, reducing the difficulty of aligning reconstructions Gaussian and expression Gaussian. If the head is move, it is hard to align them.
