### ISSUE TITLE
Tracking speed

### ISSUE THREAD

**Issue by yjhong89** [xg-chu/GAGAvatar#17]
Hi! 

About tracking, there is tracking speed difference between first tracking and next trackings.

![image](https://github.com/user-attachments/assets/8a709259-03a4-4354-8ebf-789f849e36c1)

- On V100, first tracking takes 44 seconds and tracking takes very little time after that.
- Why this happens??

Thanks!

**Comment by xg-chu** [comment]
This is due to the model compilation (JIT).
