### ISSUE TITLE
Tracker questions

### ISSUE THREAD

**Issue by yjhong89** [xg-chu/GAGAvatar#18]
Hi! Few tracker questions.

1. As you mentioned that tracker uses JIT compiler, where is that implemented in the code ?
2. VGGHead also extracts FLAME parameters but why use them from EMICA ?

**Comment by xg-chu** [comment]
1. JIT is included in the checkpoints of VGGHead and face_alignment, not included in our model or code.
2. The FLAME parameters of VGGHead are not accurate, EMICA is much better than VGGHead. But VGGHead has good head pose tracking, so we use both of them.
