### ISSUE TITLE
great work!  Is it possible to just transfer pose, or just  expression?

### ISSUE THREAD

**Issue by leeooo001** [xg-chu/GAGAvatar#2]
great work! 
Is it possible to just transfer pose, or just  expression?

**Comment by xg-chu** [comment]
Of course, it's possible to transfer only the pose or expression.
The expression is controlled by `expcode`, pose is controlled by `posecode` and `transform_matrix`.
After tracking you can use any pose and expression parameters you want (use the pose / expression parameters of input).
