### ISSUE TITLE
Multi GPUs training

### ISSUE THREAD

**Issue by endlessll** [xg-chu/GAGAvatar#20]
Thanks for your great work! I have noticed that the training code only support one GPU, and there are errors when try to use more GPUs. Since it is very helpful if the code can support Mult GPUs training when more data is collected, is there any plan to fix the Mult GPUs training problem? Thanks again.

**Comment by xg-chu** [comment]
Adding this might take some time and I'll plan it in the future.
So if you need it urgently, try to fix it yourself first.
