### ISSUE TITLE
Issue with installing diff_gaussian_rasterization

### ISSUE THREAD

**Issue by Sanoojan** [xg-chu/GAGAvatar#21]
Thanks for the work. I am facing an issue while installing diff_gaussian_rasterization using pip install ./diff-gaussian-rasterization

The detected CUDA version (11.3) mismatches the version that was used to compile
   PyTorch (12.1). Please make sure to use the same CUDA versions.
      end of output
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization_32d
  Running setup.py clean for diff_gaussian_rasterization_32d
Failed to build diff_gaussian_rasterization_32d.

Can I know what is your cuda version? And any suggestion to resolve the issue?

Current pytorch is:     
pytorch                   2.4.1           py3.12_cuda12.1_cudnn9.1.0_0    pytorch

**Comment by GeneralWhite** [comment]
Try lowering the CUDA and PyTorch versions to resolve the issue. I am using pytorch2.01+cu118 python3.11

**Comment by xg-chu** [comment]
Thank you for your attention and interest in our work.
According to the error message, maybe you need to align the cuda version. Hopefully this will solve the problem. 🚀

**Comment by xg-chu** [comment]
Installing cuda 12.1 might be a better choice. 😉
