### ISSUE TITLE
How 3d position and normal vectors are calculated ?

### ISSUE THREAD

**Issue by yjhong89** [xg-chu/GAGAvatar#22]
Hi! how these $p$ and $n$ vectors of source image are calculated??
![image](https://github.com/user-attachments/assets/d2965c48-f21d-4e78-820d-319595ff8f7b)

- Especially, this part. Since the feature plane is placed to origin, I understood cam_dirs, ray_dirs are calculated (in here)https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/data/loader_track.py#L185
  - Since R/T is w2c transformation, it means that calculate the feature plane directions in camera coordinate.. (is this right?)
- But, still don't get it why origins and distance are calculated in this way. https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/data/loader_track.py#L187
- Would you explain this in detail if don't mind ?

Thanks!

**Comment by xg-chu** [comment]
Thank you for your attention to our work! 🌟

1. This line actually compute the cam_dirs in world coordinates, and the ray_dirs is also converted to world coordinates. https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/data/loader_track.py#L185-L186
2. This line compute the camera position in world coordinates, and there may be some confusion in naming here.
Here R, T and the input matrix are consistent with the pytorch3d API, which means that the R here is actually the transpose of R in usually representation. So here we follow `-R^T*T` to calculate the position of the camera in the world coordinate system. https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/data/loader_track.py#L187
3. The `ray_dirs` is not normalized, so after multiplying any distance, `origins + distance * ray_dirs` is still the image plane. And the physical meaning of distance here is the distance to translate in the direction of the camera. This line calculate the distance of the line connecting the camera position to the world origin projected in the direction of the camera. This distance ensures that the origin of the world coordinate system is on the image plane.  https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/data/loader_track.py#L188
