### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by xz0305** [xg-chu/GAGAvatar#23]
I followed the training steps provided and iterated 200,000 times on 4,500 images with a batch size of 8, which took 140 hours. Does the paper say that the training of 586,000 images only takes 46 hours?

**Comment by xg-chu** [comment]
1. Training time is not related to the number of training images, but 4500 images are usually not enough to train a generalizable model.
2. Please make sure that an unoccupied 80G A100 GPU is used, data loading is smooth, and the environment is correctly built. 200,000 iterations should take less than 60 hours at most.

**Comment by xz0305** [comment]
Thanks for your reply, but I don't understand why the training time is independent of the number of images
________________________________
发件人: Xuangeng Chu ***@***.***>
发送时间: 2024年11月6日 11:25
收件人: xg-chu/GAGAvatar ***@***.***>
抄送: xz0305 ***@***.***>; Author ***@***.***>
主题: Re: [xg-chu/GAGAvatar] Training time (Issue #23)


  1.  Training time is not related to the number of training images, but 4500 images are usually not enough to train a generalizable model.
  2.  Please make sure that an unoccupied 80G A100 GPU is used, data loading is smooth, and the environment is correctly built. 200,000 iterations should take less than 60 hours at most.

―

**Comment by xg-chu** [comment]
As you said, the training consists of 200,000 iterations, no matter how much data there is.
