### ISSUE TITLE
Questions regarding projection matrix calculation

### ISSUE THREAD

**Issue by edhyah** [xg-chu/GAGAvatar#25]
Hello! Thank you for your great work.

Regarding the view matrix calculation, why are the x and y axes negated here? https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/libs/utils_renderer.py#L68

When computing the full projection matrix, shouldn't the calculation be proj_matrix.transpose(0, 1) @ viewmatrix? (isn't the order of operations not aligned with graphics pipelines?) https://github.com/xg-chu/GAGAvatar/blob/37698dfc011eb8b57a18f964fac6b25014b6873e/core/libs/utils_renderer.py#L73

Thanks again!

**Comment by xg-chu** [comment]
Thanks for your interest in our work. 🌟
I process the dataset in Pytorch3D coordinate system, which is defined differently than 3DGS renderer, so I negated x and y.
The order in which you calculate the full_proj_matrix also depends on whether you want to left-multiply or right-multiply the point, for this part I just keep consistent with the original 3DGS implementation.
I think it is indeed different from some common graphics pipelines. (Although many graphics pipelines are also different from each other 🤣)
