### ISSUE TITLE
Questions about Alignment and Scaling in 3D Space for Reconstruction and Driving Branches

### ISSUE THREAD

**Issue by UNIkeEN** [xg-chu/GAGAvatar#26]
Thank you for your kind and thorough response last time. 🥰

I have another question: since your final rendering result directly merges the Gaussians from both the reconstruction and driving branches, with the spatial priors for these branches provided by the DINO feature plane and the FLAME head in 3D space——

how are the position and size scales between these two planes and the FLAME head aligned in 3D space? And how was the FLAME scaling factor of 5 determined? 

Looking forward to your response～😊

**Comment by xg-chu** [comment]
These are determined when tracking the data. The tracked camera pose ensures that the head in the image matches the flame head of size 5 in canonical space.
The size of 5 is to make the size of the flame head close to 1. It's inherited from GPAvatar, which reconstructs tri-plane in unit space, and it is not important in GAGAvatar. But if you want to change this parameter, you need to re-track and re-train the model.
