### ISSUE TITLE
Paths are broken

### ISSUE THREAD

**Issue by MrNeRF** [xg-chu/GAGAvatar#3]
Hey, awesome work! 
I tried to run the inference scripts but it shows me multiple errors:

`FileNotFoundError: [Errno 2] No such file or directory: 'GAGAvatar/core/libs/GAGAvatar_track/engines/flame_model/../../assets/flame/FLAME_with_eye.pt'
`
I moved the assets from the root folder into the place where it is expected, now I get:
`FileNotFoundError: [Errno 2] No such file or directory: '/GAGAvatar/core/libs/GAGAvatar_track/engines/flame_model/../../assets/flame/FLAME_with_eye.pt'
`

I was searching the file  `FLAME_with_eye.pt`  but it is not even downloaded into the repo. It appears to me that the setup is somewhat broken?

**Comment by xg-chu** [comment]
The `assets` used in GAGAvatar_track is different from the `assets` in root. You also need to prepare the resources for GAGAvatar_track using `build_resources.sh` under `core/libs/GAGAvatar_track`, as said in https://github.com/xg-chu/GAGAvatar_track. 
I have updated the README.md for these steps.

**Comment by MrNeRF** [comment]
Works! Pretty cool!
